// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajhotmnoodkckwbqecxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqaG90bW5vb2RrY2t3YnFlY3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDAyNDksImV4cCI6MjA2MzUxNjI0OX0.76YwvwNvbo_aK0NeFJHT9eWYB2DQXxLuGZ-G5a1Qcbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);